modLoader = "javafml"
loaderVersion = "[4,)"
license = "BSD"

[[mods]]
modId = "barswap"
version = "${version}"
displayName = "BarSwap"
authors = "KesslerCascade"
description = '''
Swap your hotbar with the bottom row of your inventory using a keybind.
'''

[[dependencies.barswap]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.barswap]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "CLIENT"

